In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [2]:
bc = load_breast_cancer()

In [3]:
bc.data.shape

(569, 30)

In [4]:
bc.target.shape

(569,)

In [5]:
np.unique(bc.target)

array([0, 1])

In [6]:
bc.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [7]:
X = bc.data
y = bc.target

In [8]:
X, y

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [9]:
model = GaussianNB()
X_train, X_valid, y_train, y_valid = train_test_split(X,y)
model.fit(X,y)
classification_report(y_valid, model.predict(X_valid))

'              precision    recall  f1-score   support\n\n           0       0.98      0.89      0.94        57\n           1       0.93      0.99      0.96        86\n\n    accuracy                           0.95       143\n   macro avg       0.96      0.94      0.95       143\nweighted avg       0.95      0.95      0.95       143\n'

In [13]:
model = KNeighborsClassifier(5)
X_train, X_valid, y_train, y_valid = train_test_split(X,y)
model.fit(X,y)
classification_report(y_valid, model.predict(X_valid))

'              precision    recall  f1-score   support\n\n           0       0.96      0.95      0.96        58\n           1       0.97      0.98      0.97        85\n\n    accuracy                           0.97       143\n   macro avg       0.97      0.96      0.96       143\nweighted avg       0.97      0.97      0.96       143\n'